const q=s=>document.querySelector(s), qa=s=>Array.from(document.querySelectorAll(s));
const coarse=matchMedia('(pointer:coarse)').matches||('ontouchstart' in window);
const G={ar:{name:'ARX-41',mag:30,res:150,dmg:31,rate:90,spread:.006,reload:1450,color:0x39434a},smg:{name:'VPR-9',mag:36,res:180,dmg:24,rate:65,spread:.011,reload:1280,color:0x31383d},dmr:{name:'HMX-7',mag:18,res:90,dmg:50,rate:185,spread:.004,reload:1650,color:0x4a4d50}};
const S={tab:'play',mode:'tdm',gun:'ar',op:'RAVEN-3',veh:'WRAITH MRV',quality:'HIGH',credits:2400,run:false,pause:false,time:480,a:0,b:0,hp:100,armor:100,mag:30,reserve:150,reloading:false,next:0,yaw:0,pitch:0,vy:0,crouch:false,ads:false,vehicle:false,sprint:false,mats:6,grenades:2,move:{x:0,y:0},keys:{},bots:[],obs:[],caps:[],loot:false,done:false,sens:1,zoneRadius:145,attachments:new Set(['optic'])};
let scene,camera,rend,ray,weapon,muzzle,rover,last=performance.now(),rad=q('#radar').getContext('2d'),F=new THREE.Vector3(),R=new THREE.Vector3(),T=new THREE.Vector3(),aud=null,gun=G.ar,terrain;
function bindLobby(){qa('.sideNav button').forEach(b=>b.addEventListener('click',()=>{const nav=b.parentElement;nav.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b))}));qa('[data-attachment]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.attachment;if(S.attachments.has(a)){S.attachments.delete(a);b.classList.remove('on')}else{S.attachments.add(a);b.classList.add('on')}q('#attachCount').textContent=S.attachments.size+' / 4 EQUIPPED'}));qa('.tab').forEach(b=>b.addEventListener('click',()=>{S.tab=b.dataset.tab;qa('.tab').forEach(x=>x.classList.toggle('on',x===b));qa('.panelView').forEach(v=>v.classList.toggle('on',v.id===S.tab))}));qa('.modeCard').forEach(b=>b.addEventListener('click',()=>{S.mode=b.dataset.mode;qa('.modeCard').forEach(x=>x.classList.toggle('on',x===b))}));qa('[data-gun]').forEach(b=>b.addEventListener('click',()=>setLobbyGun(b.dataset.gun)));qa('[data-select-gun]').forEach(c=>c.addEventListener('click',()=>{setLobbyGun(c.dataset.selectGun);qa('[data-select-gun]').forEach(x=>{x.classList.toggle('on',x===c);x.querySelector('button').textContent=x===c?'EQUIPPED':'EQUIP'})}));qa('[data-op]').forEach(c=>c.addEventListener('click',()=>{S.op=c.dataset.op;q('#lobbyOp').textContent=S.op;qa('[data-op]').forEach(x=>{x.classList.toggle('on',x===c);x.querySelector('button').textContent=x===c?'EQUIPPED':'EQUIP'})}));qa('[data-veh]').forEach(c=>c.addEventListener('click',()=>{S.veh=c.dataset.veh;q('#lobbyVeh').textContent=S.veh;qa('[data-veh]').forEach(x=>{x.classList.toggle('on',x===c);x.querySelector('button').textContent=x===c?'EQUIPPED':'EQUIP'})}));qa('[data-buy]').forEach(b=>b.addEventListener('click',()=>{const p=Number(b.dataset.buy);if(S.credits>=p&&!b.disabled){S.credits-=p;b.textContent='OWNED';b.disabled=true;q('#credits').textContent=S.credits.toLocaleString()+' CR'}}));q('#deploy').addEventListener('click',start)}
function setLobbyGun(k){S.gun=k;q('#lobbyGun').textContent=G[k].name;qa('[data-gun]').forEach(x=>x.classList.toggle('on',x.dataset.gun===k))}
bindLobby();
function mat(c,r=.86,m=0){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m})}
function mesh(g,m,x=0,y=0,z=0){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);return o}
function box(x,y,z,w,h,d,c=0x60625f,solid=true){const o=mesh(new THREE.BoxGeometry(w,h,d),mat(c),x,y,z);if(solid)S.obs.push({min:new THREE.Vector3(x-w/2,y-h/2,z-d/2),max:new THREE.Vector3(x+w/2,y+h/2,z+d/2)});return o}
function start(){q('#lobby').classList.add('hide');q('#game').classList.remove('hide');gun=G[S.gun];S.time=S.mode==='br'?900:480;S.mag=gun.mag;S.reserve=gun.res;init3();makeWorld();weaponModel();spawnBots(S.mode==='br'?23:12);controls();hud();S.run=true;requestAnimationFrame(loop)}
function init3(){scene=new THREE.Scene();scene.background=new THREE.Color(0x87949a);scene.fog=new THREE.FogExp2(0x889296,S.quality==='LOW' ? .012 : .007);camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.06,520);camera.position.set(0,2.2,42);camera.rotation.order='YXZ';rend=new THREE.WebGLRenderer({antialias:S.quality!=='LOW',powerPreference:'high-performance'});rend.setSize(innerWidth,innerHeight);rend.setPixelRatio(Math.min(devicePixelRatio,S.quality==='ULTRA'?2:S.quality==='HIGH'?1.55:1.15));rend.shadowMap.enabled=S.quality!=='LOW';rend.shadowMap.type=THREE.PCFSoftShadowMap;rend.toneMapping=THREE.ACESFilmicToneMapping;rend.toneMappingExposure=1.05;q('#view').appendChild(rend.domElement);scene.add(new THREE.HemisphereLight(0xdde7ec,0x3d3b35,1.5));const sun=new THREE.DirectionalLight(0xffe5b8,2.5);sun.position.set(-65,90,45);sun.castShadow=S.quality!=='LOW';sun.shadow.mapSize.set(S.quality==='ULTRA'?2048:1024,S.quality==='ULTRA'?2048:1024);sun.shadow.camera.left=-150;sun.shadow.camera.right=150;sun.shadow.camera.top=150;sun.shadow.camera.bottom=-150;scene.add(sun);ray=new THREE.Raycaster();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();rend.setSize(innerWidth,innerHeight)})}
