name: OnlyWar Unity Native Build
on:
  workflow_dispatch:
    inputs:
      target:
        description: Build target
        required: true
        type: choice
        default: WebGL
        options:
          - WebGL
          - StandaloneWindows64
          - Android
          - iOS

jobs:
  unity:
    name: Build OnlyWar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/cache@v4
        with:
          path: OnlyWarUnity/Library
          key: OnlyWarUnity-Library-${{ hashFiles('OnlyWarUnity/Assets/**', 'OnlyWarUnity/Packages/**', 'OnlyWarUnity/ProjectSettings/**') }}
          restore-keys: OnlyWarUnity-Library-
      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: OnlyWarUnity
          targetPlatform: ${{ inputs.target }}
          buildName: OnlyWar
          buildsPath: build
      - uses: actions/upload-artifact@v4
        with:
          name: OnlyWar-${{ inputs.target }}
          path: build
